test_that("parse_dcf handles simple and multi-line fields", {
  text <- paste0(
    "Package: mypkg\n",
    "Version: 1.2.3\n",
    "Description: A package that does\n",
    "    lots of useful things\n",
    "    across several lines.\n",
    "Imports: dplyr,\n",
    "    ggplot2,\n",
    "    tidyr\n",
    "License: MIT\n"
  )
  d <- parse_dcf(text)

  expect_equal(d[["Package"]], "mypkg")
  expect_equal(d[["Version"]], "1.2.3")
  expect_equal(d[["License"]], "MIT")
  # Multi-line Description is folded (contains "lots of")
  expect_true(grepl("lots of", d[["Description"]]))
  # Multi-line Imports is folded
  expect_true(grepl("ggplot2", d[["Imports"]]))
})

test_that("parse_dcf: last value wins on duplicate fields", {
  text <- "Key: first\nKey: second\n"
  d <- parse_dcf(text)
  expect_equal(d[["Key"]], "second")
})

test_that("parse_dcf returns empty list for blank input", {
  expect_equal(parse_dcf(""),      list())
  expect_equal(parse_dcf("   \n"), list())
  expect_equal(parse_dcf(NULL),    list())
})

test_that("parse_namespace handles export() with multiple symbols", {
  ns <- parse_namespace("export(foo, bar, baz)\n")
  expect_true("foo" %in% ns$exports)
  expect_true("bar" %in% ns$exports)
  expect_true("baz" %in% ns$exports)
})

test_that("parse_namespace handles exportPattern()", {
  ns <- parse_namespace('exportPattern("^[A-Z]")\n')
  expect_true(any(grepl("pattern:", ns$exports, fixed = TRUE)))
  expect_true(any(grepl("[A-Z]", ns$exports)))
})

test_that("parse_namespace handles importFrom() with multiple functions", {
  ns <- parse_namespace("importFrom(dplyr, select, filter, mutate)\n")
  expect_true("dplyr::select" %in% ns$importFrom)
  expect_true("dplyr::filter" %in% ns$importFrom)
  expect_true("dplyr::mutate" %in% ns$importFrom)
})

test_that("parse_namespace handles S3method()", {
  ns <- parse_namespace("S3method(print, myclass)\nS3method(summary, myclass)\n")
  expect_true("print.myclass"   %in% ns$S3method)
  expect_true("summary.myclass" %in% ns$S3method)
})

test_that("parse_namespace handles useDynLib()", {
  ns <- parse_namespace("useDynLib(mypkg, .registration = TRUE)\n")
  expect_true("mypkg" %in% ns$useDynLib)
})

test_that("parse_namespace ignores comment lines", {
  text <- "# Generated by roxygen2\nexport(foo)\n# S3method(print, bar)\n"
  ns <- parse_namespace(text)
  expect_true("foo" %in% ns$exports)
  expect_false("print.bar" %in% ns$S3method)
})

test_that("parse_namespace returns empty vectors for blank input", {
  ns <- parse_namespace("")
  expect_equal(ns$exports,    character(0L))
  expect_equal(ns$importFrom, character(0L))
  expect_equal(ns$S3method,   character(0L))
  expect_equal(ns$useDynLib,  character(0L))
})

test_that("parse_namespace handles a mixed realistic NAMESPACE file", {
  text <- paste0(
    "# Generated by roxygen2: do not edit by hand\n",
    "export(fit_model)\n",
    "export(predict_model, summary_model)\n",
    "exportPattern(\"^\\\\.[A-Z]\")\n",
    "S3method(print, mymodel)\n",
    "S3method(coef, mymodel)\n",
    "importFrom(stats, lm, glm)\n",
    "importFrom(Matrix, Matrix)\n",
    "useDynLib(mypkg, .registration = TRUE)\n"
  )
  ns <- parse_namespace(text)
  expect_true("fit_model"       %in% ns$exports)
  expect_true("predict_model"   %in% ns$exports)
  expect_true("summary_model"   %in% ns$exports)
  expect_true(any(grepl("pattern:", ns$exports)))
  expect_true("print.mymodel"   %in% ns$S3method)
  expect_true("coef.mymodel"    %in% ns$S3method)
  expect_true("stats::lm"       %in% ns$importFrom)
  expect_true("stats::glm"      %in% ns$importFrom)
  expect_true("Matrix::Matrix"  %in% ns$importFrom)
  expect_true("mypkg"           %in% ns$useDynLib)
})

test_that("build_context exposes all required fields and methods", {
  file_map <- list(
    "DESCRIPTION" = "Package: mypkg\nVersion: 2.0\nLicense: GPL-2\n",
    "NAMESPACE"   = "export(foo)\nimportFrom(dplyr, select)\n",
    "R/foo.R"     = "foo <- function() 1\n",
    "man/foo.Rd"  = "\\name{foo}\n"
  )
  read_fn <- function(p) file_map[[p]] %||% ""
  files   <- names(file_map)

  churn <- data.frame(
    file    = "R/foo.R",
    added   = 1L,
    deleted = 0L,
    stringsAsFactors = FALSE
  )
  prev_exp <- c("old_export")

  ctx <- build_context("mypkg", "2.0", "2.0", "2024-01-01",
                       files, read_fn,
                       churn_df = churn, prev_exports = prev_exp)

  # Identity fields
  expect_equal(ctx$package,      "mypkg")
  expect_equal(ctx$version,      "2.0")
  expect_equal(ctx$ref,          "2.0")
  expect_equal(ctx$date,         "2024-01-01")
  expect_equal(sort(ctx$files),  sort(files))

  # read() returns content or "" for absent
  expect_true(grepl("mypkg", ctx$read("DESCRIPTION")))
  expect_equal(ctx$read("not_there.R"), "")

  # lines() splits on newlines
  lns <- ctx$lines("R/foo.R")
  expect_true(is.character(lns))
  expect_true(length(lns) >= 1L)
  expect_true(any(grepl("foo", lns)))

  # exists()
  expect_true(ctx$exists("R/foo.R"))
  expect_false(ctx$exists("R/missing.R"))

  # find()
  r_files <- ctx$find("^R/")
  expect_true("R/foo.R" %in% r_files)
  expect_false("man/foo.Rd" %in% r_files)

  # desc (lazy)
  expect_equal(ctx$desc[["Package"]], "mypkg")
  expect_equal(ctx$desc[["License"]], "GPL-2")

  # namespace (lazy)
  expect_true("foo" %in% ctx$namespace$exports)
  expect_true("dplyr::select" %in% ctx$namespace$importFrom)

  # churn
  expect_equal(nrow(ctx$churn), 1L)
  expect_equal(ctx$churn$file, "R/foo.R")

  # prev_exports
  expect_equal(ctx$prev_exports, "old_export")
})

test_that("build_context read() is memoised (read_fn called once per path)", {
  call_count <- 0L
  read_fn <- function(p) {
    call_count <<- call_count + 1L
    if (p == "DESCRIPTION") "Package: x\nVersion: 1.0\n" else ""
  }
  ctx <- build_context("x", "1.0", "1.0", "2024-01-01",
                       c("DESCRIPTION"), read_fn)

  ctx$read("DESCRIPTION")
  ctx$read("DESCRIPTION")
  ctx$read("DESCRIPTION")

  expect_equal(call_count, 1L)
})

test_that("build_context null churn_df becomes empty data.frame", {
  ctx <- build_context("p", "1.0", "1.0", "2024-01-01",
                       character(0L), function(p) "")
  expect_s3_class(ctx$churn, "data.frame")
  expect_equal(nrow(ctx$churn), 0L)
  expect_true(all(c("file", "added", "deleted") %in% colnames(ctx$churn)))
})
